### ISSUE TITLE
helm upgrade with --reuse-values fails to template pvc.yaml

### ISSUE THREAD

**Issue by ryanelliottsmith** [rancher/rancher#30190]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Install Rancher from a helm chart from before custom Logos were added:
`helm install rancher rancher-stable/rancher --namespace cattle-system --set hostname=test.example.com --set ingress.tls.source=secret --version 2.4.8 --set replicas=1`
1. Attempt to upgrade to >2.5.x with --reuse-values:
`helm upgrade rancher rancher-stable/rancher -n cattle-system --reuse-values --version 2.5.2`

**Result:**
```
Error: UPGRADE FAILED: template: rancher/templates/pvc.yaml:1:19: executing "rancher/templates/pvc.yaml" at <.Values.customLogos.enabled>: nil pointer evaluating interface {}.enabled
```

**Other details that may be helpful:**
It is possible to export the current values to a file and then reference that file during upgrade:
```
helm get values rancher -n cattle-system -o yaml > values.yaml
helm upgrade rancher rancher-stable/rancher -n cattle-system  -f values.yaml --version 2.5.2
```
This results in helm correctly merging the defined values with the new values.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): < 2.5.x
- Installation option (single install/HA): k8s via helm

gz#13571

gz#13836

**Comment by ansilh** [comment]
This issue is related to `helm`.
The error is pointing to the value ; `Values.customLogos.enabled`

In our chart, we are using the below in `values.yaml` which contains nested defaults and which won't work.

```
# Rancher custom logos persistence
customLogos:
  enabled: false
  volumeSubpaths:
    emberUi: "ember"
    vueUi: "vue"
....
```
Ref: https://github.com/helm/helm/issues/8026#issuecomment-695761966

**Comment by ansilh** [comment]
Tried to set `customLogos.enabled=false` , but it failed in `Values.customLogos.volumeKind` with incompatible type.
```
 ./helm upgrade  rancher rancher-stable/rancher -n cattle-system --reuse-values --version 2.5.7 --set customLogos.enabled=false
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: kube_config_cluster.yml
Error: UPGRADE FAILED: template: rancher/templates/pvc.yaml:1:42: executing "rancher/templates/pvc.yaml" at <eq .Values.customLogos.volumeKind "persistentVolumeClaim">: error calling eq: incompatible types for comparison
```

Below one worked.

```
 ./helm upgrade  rancher rancher-stable/rancher -n cattle-system --reuse-values --version 2.5.7 --set customLogos.enabled=false --set customLogos.volumeKind=persistentVolumeClaim
```

**Comment by ansilh** [comment]
The `customLogos` changes were introduced by the PR https://github.com/rancher/rancher/pull/29443

**Comment by ansilh** [comment]
This issue was also reported during the 2.5.7 to 2.5.8 upgrade.
```
❯ helm list -n cattle-system
NAME NAMESPACE REVISION UPDATED STATUS CHART APP VERSION
rancher cattle-system 3 2021-03-16 10:06:39.608749572 -0700 PDT deployed rancher-2.5.7 v2.5.7
rancher-webhook cattle-system 1 2021-03-16 17:08:28.712681045 +0000 UTC deployed rancher-webhook-0.1.0-beta901 0.1.0-beta9

❯ helm upgrade rancher rancher-stable/rancher --reuse-values --version=2.5.8 -n cattle-system

Error: UPGRADE FAILED: template: rancher/templates/post-delete-hook-service-account.yaml:1:14: executing "rancher/templates/post-delete-hook-service-account.yaml" at <.Values.postDelete.enabled>: nil pointer evaluating interface {}.enabled
```

**Comment by nataz77** [comment]
I'm hitting the same problem when upgrading from v2.5.5 to v2.6

```bash
❯ helm upgrade --reuse-values rancher rancher-latest/rancher -n cattle-system --version=2.6
Error: UPGRADE FAILED: template: rancher/templates/post-delete-hook-service-account.yaml:1:14: executing "rancher/templates/post-delete-hook-service-account.yaml" at <.Values.postDelete.enabled>: nil pointer evaluating interface {}.enabled
```

The error is the same mentioned in the comment by @ansilh in the comment above

**Comment by cbron** [comment]
What's actually happening here is not related to default, it's how helm's reuse-values works: 
See: https://github.com/helm/helm/issues/3957#issuecomment-384685681

You'll need to workaround this for your case based on how you deploy helm, see above for help.
