### ISSUE TITLE
ui-index is not updated to local when upgrade from Rancher 2.1.x HA setup

### ISSUE THREAD

**Issue by Leen15** [rancher/rancher#19327]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- Try to enable fluentd logging on a imported cluster (created with RKE)
- Set endpoint with my fluentd instance (ex. XXX.XXX.XXX.XXX:24224)
- Set the shared key as the same of my fluentd instance

**Result:**
Test Button answers as "Settings validated"
Save button generates a "t is not a function" error

**Environment information**
- Rancher version: 2.2.1
- Installation option (single install/HA): HA

**Comment by loganhz** [comment]
@Leen15 Can you always reproduce it ?

**Comment by loganhz** [comment]
@Leen15 Can you check the `ui-index` settings? Under Global level menu -> Settings

**Comment by alena1108** [comment]
@Leen15 is it a fresh 2.2.1 install, or have you upgraded to it from some older rancher version?

**Comment by kingsd041** [comment]
@loganhz  I did not reproduce this issue

Test steps:
1. Single node installation rancher(v2.2.1)
2. Add a custom cluster
3. Enable fluentd logging and configure the correct Endpoint/Shared Key/Username/Password/Hostname
4. Test Button answers as "Settings validated"

Then I click on the `SAVE` button and I will be prompted to save successfully, and there is no "t is not a function" error.

**Comment by Leen15** [comment]
I have an imported cluster of 4 hosts, created with RKE.
Rancher is not a fresh install but an upgrade from the 2.1.7 version, upgraded with helm.
I can reproduce it every time I press save, the same error appears also if I try to configure Elasticsearch instead of fluentd.
I can confirm that the app "rancher-logging" exists inside the system namespace and the logging works.

**Comment by Leen15** [comment]
> @Leen15 Can you check the `ui-index` settings? Under Global level menu -> Settings

The value is:
https://releases.rancher.com/ui/latest2/index.html

**Comment by loganhz** [comment]
@Leen15 please change it to `local`

https://releases.rancher.com/ui/latest2/index.html will keep changing as we are working on 2.3

**Comment by loganhz** [comment]
Did you change it by yourself ?

**Comment by Leen15** [comment]
> Did you change it by yourself ?

No I didn't, i was with Rancher 2.1.7 in HA setup with helm. I changed the helm repo to latest and upgraded to 2.2.1.

**Comment by Leen15** [comment]
I confirm that with "local" value in ui-index it works.

**Comment by Leen15** [comment]
Sorry but after changed the ui-index value I tried to set logging as "none" and the "rancher-logging" app was still there so I removed it.
Now I'm trying to enable again fluentd but after the "saved" confirm, no app is created on system namespace... how can I force it?

**Comment by loganhz** [comment]
@Leen15 is it Project level logging?

I cannot reproduce this issue. I delete the rancher-logging app manually. And re-enable monitoring. The app came back

**Comment by Leen15** [comment]
I'm trying with cluster level logging.
Is there a way to force it? Where can I see if there is some error? 
I also tried to delete the cattle-logging namespace but rancher doesn't recreate it when I enable the logging.

**Comment by Leen15** [comment]
I just tried to enable a project level logging, and it deployed also the app for cluster logging! I don't know how it's possible :)

**Comment by aiwantaozi** [comment]
Hi @Leen15 fluentd is a daemonset, cluster and project logging both use this daemonset, rancher will check whether the fluentd app is deployed when changes happened(enable cluster logging/enable project logging, update logging configure), at this time, if not fluentd app is deployed, rancher will deployed it. When you happen to delete the app, just update logging configure or reenable it to trigger the deploy.

**Comment by Leen15** [comment]
Thanks for the explain @aiwantaozi . 
I tried multiple times to configure again and to reenable the logging for the cluster but nothing happened.
When I enabled the logging for a project, then it deployed the rancher-logging app.
I don't know what is gone wrong, but now it's ok.

**Comment by aiwantaozi** [comment]
@Leen15 I tried but can't reproduce. Could you check whether the cluster level logging could work? if all the loggings disabled, then fluentd app is deleted. Try to enable/disable cluster logging, could the app get deployed/deleted, it needs some time to clean all the daemonset. Thanks.

**Comment by Leen15** [comment]
I tried to disable the cluster logging. I don't have any project with logging enabled.
After 10 minutes the app is there, active, and it sends data to my ELK stack.
![Immagine 5152](https://user-images.githubusercontent.com/3629071/55478774-cd015380-561c-11e9-815e-dbe7bcf1f216.png)
![Immagine 5153](https://user-images.githubusercontent.com/3629071/55478775-cd015380-561c-11e9-957c-6305f546f561.png)

**Comment by Leen15** [comment]
1 HOUR later, the app get deleted.

**Comment by aiwantaozi** [comment]
I tried 3 node HA mode and import a rke cluster but could not reproduce, could you check rancher server log when you disable logging? Where are your rancher server nodes and imported cluster nodes? Thanks

**Comment by Leen15** [comment]
This is my configuration:
- 3 nodes rke cluster (dedicated servers in different datacenters, different providers) with rancher installed in HA using helm
- 4 nodes rke cluster (dedicated servers in different datacenters, same provider ) 

I'm testing the logging function on the second cluster.
Is there a way to see the rancher log centralized from the UI? Or I have to check the log of every node of the rancher cluster manually?

**Comment by aiwantaozi** [comment]
You can see the rancher server logs in the first cluster -> system project -> cattle-system namespace -> rancher workload

**Comment by Leen15** [comment]
This is the log of the three nodes:

https://pastebin.com/vNbTy7qK

No specific logs after the delete (log records are 3 minutes older than the delete action)

**Comment by cjellick** [comment]
is this issue the same as this one? https://github.com/rancher/rancher/issues/19213

**Comment by alena1108** [comment]
@logan there is no magic background thread changing the index on 2.1.x,  so there is no proof for theory explained in: https://github.com/rancher/rancher/pull/19357#issuecomment-479687998

Here is what I think happens:

=======================================
On 2.1.x, ui-index was never respected on production setups (having image tag prefixed with "v")
On 2.2.x., ui-index is respected on all the setups

It explains issue1 hit on airgap setup - https://github.com/rancher/rancher/issues/19213. User changed the value to https://test/ui/latest2/index.html, and it had 0 effect on 2.1.x (most likely user changed it thinking it would take effect? not sure). But upon upgrade to 2.2.x, we started respecting the setting, and things broke. 

Now this very issue2 - when on upgrade, the setting value wasn't changed to local and remained "https://releases.rancher.com/ui/latest2/index.html"

The ui-index value gets set to "local" (passed via an environment variable) on 2.2.x only when the setting was never modified on 2.1.x. There is a "customized" flag on per setting basis that reflects if the value was ever modified. If user ever hit save on a setting even w/o modifying it on 2.1.x, the setting gets marked as customized and never gets updated to "local" upon upgrade to 2.2.x.

We are going to:
* Document this issue for 2.2.2 with the workaround of changing the ui index to local
* Post 2.2.2, figure out a proper fix (if there is any)

**Comment by alena1108** [comment]
Steps to reproduce for qa:

1) Start rancher server 2.1.x
2) Go to Settings in the UI, open ui-index setting, click save w/o making any modifications
3) Upgrade rancher server to 2.2x. The ui-index doesn't get reset to "local", and remains to be "https://releases.rancher.com/ui/latest2/index.html"

If step 2) is skipped, or fresh install of 2.2.x is done, ui-index gets set to "local" as it's supposed to.

**Comment by loganhz** [comment]
@Leen15 did you hit save on a setting even w/o modifying it on 2.1.x ?

**Comment by loganhz** [comment]
> @logan there is no magic background thread changing the index on 2.1.x, so there is no proof for theory explained in: #19357 (comment)

@alena1108 @cjellick during the startup it will change the default 

Here is the code for the magic thing https://github.com/rancher/rancher/blob/release/v2.1/pkg/api/controllers/settings/settings.go#L97

I don't think @Leen15 hit the save manually.

**Comment by Leen15** [comment]
I confirm, I never hit save button in that page before you asked me.

**Comment by alena1108** [comment]
>> @alena1108 @cjellick during the startup it will change the default
>> Here is the code for the magic thing >> https://github.com/rancher/rancher/blob/release/v2.1/pkg/api/controllers/settings/settings.go#L97

@loganhz This code only runs at the rancher startup, during the scaled context registration to set the settings' value to the environment variable values. There is no magic control loop that would restore things to 2.1.7 defaults in etcd after 2.1.7 container is already running. So when HA upgrade happens, the only new containers that are starting up, are 2.2.2 containers. 

 Also the value would never be restored even on the startup when it's been customized.

**Comment by alena1108** [comment]
@Leen15 can you click "View in API" for the ui-index settings, and post the output here?

**Comment by Leen15** [comment]
```
{
"annotations": {
"lifecycle.cattle.io/create.cat-setting-controller": "true"
},
"baseType": "setting",
"created": "2019-02-19T17:29:42Z",
"createdTS": 1550597382000,
"creatorId": null,
"customized": true,
"default": "https://releases.rancher.com/ui/latest2/index.html",
"id": "ui-index",
"labels": {
"cattle.io/creator": "norman"
},
"links": {
"remove": "…/v3/settings/ui-index",
"self": "…/v3/settings/ui-index",
"update": "…/v3/settings/ui-index"
},
"name": "ui-index",
"source": "db",
"type": "setting",
"uuid": "f0fc7ecd-346b-11e9-a186-0cc47a84f012",
"value": "local"
}
```

**Comment by alena1108** [comment]
@loganhz based on @Leen15 comment, "default" value still keeps the old value. Whether Save is hit or not hit, this value should have been overridden on a startup, and that didn't happen. That invalidates my theory https://github.com/rancher/rancher/issues/19327#issuecomment-480073197 for this particular issue. The theory is still correct for https://github.com/rancher/rancher/issues/19213 where the setting was customized.
