### ISSUE TITLE
[2.5] u.replaceWith is not a function

### ISSUE THREAD

**Issue by nickgerace** [rancher/rancher#29676]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Upgrade from 2.4.5 to 2.5.1 with Kubernetes v1.18.5
2. Log in to the cluster (_need more info on which user_). 

**Result:**
![image](https://user-images.githubusercontent.com/39320683/96766125-9b8bdc80-13a8-11eb-8761-e0994f005d78.png)

**Other details that may be helpful:**
This upgrade works on Kubernetes v1.15.2 without problems.

This issue is filed from the forum post: https://forums.rancher.com/t/u-replacewith-is-not-a-function/18627

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.1
- Installation option (single install/HA):  _need more info_

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): _need more info_
- Machine type (cloud/VM/metal) and specifications (CPU/memory): _need more info_
- Kubernetes version (use `kubectl version`): _need more info_

```
(paste the output here)
```

- Docker version (use `docker version`): _need more info_

```
(paste the output here)
```

**Comment by nickgerace** [comment]
Information needed... 

1. What was the user that was being attempted to login with? Was it the Admin user?
2. What was the installation option (single install/HA)?
3. What was the cluster type (Hosted/Infrastructure Provider/Custom/Imported)?
4. What was the machine type (cloud/VM/metal) and specifications (CPU/memory)?
5. What is the output when running ```kubectl version```?
6. What is the output when running ```docker version```?

**Comment by BigKAA** [comment]
> Information needed...
> 
> 1. What was the user that was being attempted to login with? Was it the Admin user?
Admin user

> 2. What was the installation option (single install/HA)?
single docker install
docker run -d --restart=unless-stopped --privileged  -p 80:80 -p 443:443   -v /opt/rancher:/var/lib/rancher   rancher/rancher:latest

> 3. What was the cluster type (Hosted/Infrastructure Provider/Custom/Imported)?
Imported

> 4. What was the machine type (cloud/VM/metal) and specifications (CPU/memory)?
**rancher:** vmware RAM 4GB, 2 CPU
**k8s 1.18:** vmware 3 vm - 6 CPU, 12Gb RAM
**k8s 1.15:** vmware 2 vm, - 6 CPU, 12 GB RAM

> 5. What is the output when running `kubectl version`?
**k8s 1.15:**
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:23:26Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:15:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

**k8s 1.18:**
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:39:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

> 6. What is the output when running `docker version`?
**k8s 1.15:**
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:46:54 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:45:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**k8s 1.18:**
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:46:54 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:45:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Rancher host:**
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:46:54 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:45:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by denitol** [comment]
I have the same error.


for my import kubernetes-cluster version v1.15.10

**Comment by jiaqiluo** [comment]
I cannot reproduce the bug in the upgrade path from `v2.4.5` to `v2.5.1` single install 

Step:
- run rancher v2.4.5 single-install
- log in as a standard user
- provision one cluster for each supported k8s versions 
- imported an RKE cluster with k8s version `v1.15.12-rancher2-6` 
![image](https://user-images.githubusercontent.com/6218999/98607941-67208780-22a7-11eb-9539-824127a5f942.png)
- add another standard user as the cluster member of all the above clusters 
- upgrade Rancher to v2.5.1

Results:

Admin, cluster owner, and cluster member can open the cluster page of all clusters without seeing any errors. 
The error in the issue is NOT seen for both the rancher-provisioned k8s 1.15 cluster and the imported k8s 1.15 cluster.

**Comment by gaktive** [comment]
By all accounts, this doesn't look reproducible by QA or UI anymore. @jiaqiluo, shall we close this and either reopen this or create a new ticket if it pops up again?

**Comment by jiaqiluo** [comment]
This issue is closed since it is not reproducible. 

Be free to reopen the issue if you hit it. 
If possible, please provide steps and information about your setup so we can try to reproduce it.
