### ISSUE TITLE
Rancher 2.2.2 CronJob View/Edit Yaml Failed

### ISSUE THREAD

**Issue by panho66** [rancher/rancher#20101]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug, Work ok in 2.1.6 but failed in 2.2.2

**Steps to reproduce (least amount of steps as possible):**
Deploy CronJob from UI
Goto UI view/edit yaml for CronJob just created

**Result:**
![image](https://user-images.githubusercontent.com/15118220/57429676-723cc680-7270-11e9-861f-2fbfe8065b8c.png)

![image](https://user-images.githubusercontent.com/15118220/57429473-977d0500-726f-11e9-9041-5704febd0aa8.png)

Rancher logs
2019/05/09 05:32:29 [ERROR] Upstream ResponseWriter of type responsewriter.ContentTypeWriter does not implement http.CloseNotifier

**Other details that may be helpful:**

**Environment information**
- Rancher version 2.2.2

**Comment by marcusaram** [comment]
Having same issues when editing ConfigMap, if you select View/Edit YAML same error is shown in 2.2.2

**Comment by stevenklar** [comment]
I found this issue also with other resources. Only we found workaround is directly editing with kubectl.

**Comment by superseb** [comment]
Seems to be the same as https://github.com/rancher/rancher/issues/19723
