### ISSUE TITLE
Node Template Driver isn't loading anymore

### ISSUE THREAD

**Issue by mxschmitt** [rancher/rancher#13455]
**Rancher versions:**
rancher/ui: v2.0.42

**Steps to Reproduce:**

- Add the hcloud UI Driver: https://github.com/mxschmitt/ui-driver-hetzner
- add a node template
- error appears

**Results:**

```javascript
opcode-compiler.js:36 Uncaught TypeError: (0 , this.funcs[r]) is not a function
    at e.compile (opcode-compiler.js:36)
    at n.i.expr (opcode-compiler.js:1157)
    at n.i.compileParams (opcode-compiler.js:1509)
    at n.i.compileArgs (opcode-compiler.js:1520)
    at n.i.modifier (opcode-compiler.js:1283)
    at opcode-compiler.js:70
    at e.compile (opcode-compiler.js:36)
    at e.compile (opcode-compiler.js:763)
    at Object.evaluate (runtime.js:493)
    at e.evaluate (runtime.js:30)
```

In the rancher/ui: `v2.0.42` release the error does not appear. Currently the the complete web application will crash.

Related issue: https://github.com/mxschmitt/ui-driver-hetzner/issues/13

**Comment by loganhz** [comment]
Hi @mxschmitt , 
I can reproduce this issue with UI `v2.0.42`.

As we have upgraded `ember` to `v3.X` from `v2.X` few days ago.
The `ember-template-compiler` in `ui-driver-skel` is out of date now.

Can you upgrade it in your `ui-driver-hetzner` and run `npm run build` again, please?
Here is the example https://github.com/rancher/ui-driver-skel/pull/9/files

But the new ui-driver build will work for rancher 2.0.1 and above. 
It doesn't work in 2.0.0 

If you want to build a ui-driver for both 2.0.0 and 2.0.1, you might need to do something like
```
Ember.VERSION === '2.16.2' ? compliedTemplatesWithOldTemplateCompiler : compliedTemplatesWithNewTemplateCompiler
```
in your `ui-driver-hetzner/component.js`

Thanks
