### ISSUE TITLE
[BUG] After monitoring upgrade from 100.1.3+up19.0.3 to 100.2.0+up40.1.2, user won't receive an alert.

### ISSUE THREAD

**Issue by vivek-infracloud** [rancher/rancher#40358]
**Rancher Server Setup**
- Rancher version: v2.6.9
- Installation option (Docker install/Helm Chart): Docker

**Information about the Cluster**
- Kubernetes version: Any k8s version
- Cluster Type (Local/Downstream): Downstream

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin

**Describe the bug**

After upgrading Monitoring chart from 100.1.3+up19.0.3 to 100.2.0+up40.1.2, user won't receive an alert. 

The above failure is caused by the way `receivers: name` is set in alerting configuration in monitoring version `100.1.3+up19.0.3` Vs. `100.2.0+up40.1.2`

**To Reproduce**

1. Install previous version - 100.1.3+up19.0.3
2. Install alerting version - 100.0.3
3. Test monitoring p0 test cases - **PASS**
4. Test alertmanager p0 test cases - **PASS** (Successfully received alert on telegram)
5. Upgrade monitoring chart to latest version - 100.2.0+up40.1.2

The above failure is caused the way `receivers: name` is set in alerting configuration in monitoring version `100.1.3+up19.0.3` Vs. `100.2.0+up40.1.2`

**Result**
After upgrade, failed to receive alert on telegram. Following error was seen in alerting-sachet pod.
`2023/01/19 14:08:38 main.go:247: Error: {"Error":true,"Status":400,"Message":"Receiver missing: default/amc-7/prom2sms"}Thu, Jan 19 2023 7:39:38 pm`

**Expected Result**
User should receive the alert on telegram that was configured in Step 4.

**Comment by OA72280** [comment]
In Rancher v2.7.0 noticed that when you create a new cluster, and attempt to install the Monitoring chart, after clicking install, it's a blank screen. Usually you're met with a screen to edit yaml to inject (plugins, etc) and then execute the deployment....

**Comment by geethub97** [comment]
steps to bypass this issue as this was a change introduced by the upstream chart: 
update the sachet receiver name to follow the convention to change the test cases to use '/' as a delimiter instead of instead of '-'

**Comment by ronhorton** [comment]
reopening to determine disposition/create tracking ticket

**Comment by prachidamle** [comment]
This should be documented in the docs.

**Comment by martyav** [comment]
> This change was introduced by upstream to avoid collisions with AlertManagerConfig objects.
> 
> steps to bypass this issue from Rancher UI:
> 
> 1. Navigate to ConfigMaps under More Resources -> Core -> ConfigMaps or by searching ConfigMaps
> 2. Find the receivers config maps  and edit by clicking the three dots in the corner -> edit.
> 3. Update the receiver name to use '/' as a delimiter instead of instead of '-': '<namespace>/<alertmanagerconfig-name>/<receiver-name>' (i.e: default/amc-7/prom2sms)
> 4. restart the alert manager and receiver pods to ensure config is reloaded properly from Workloads -> Pods
> 
> Upstream PR/Release Notes: [prometheus-operator/prometheus-operator@80a72c4](https://github.com/prometheus-operator/prometheus-operator/commit/80a72c42f5c62012d27330b7c5203fd110d7f764) [prometheus-operator/prometheus-operator#4626](https://github.com/prometheus-operator/prometheus-operator/pull/4626)

I'm working on a PR for rancher-docs describing these steps. 

Questions -- 
Is there a certain indication that the user can use to find the receiver's config map (special name, prefix, namespace, etc.?)
For step 2, does the user select edit config, or edit yaml?
For step 3, how/where does the user update the delimiter?

**Comment by geethub97** [comment]
@martyav 

Below are the updated details for the AlertManagerConfig. The changes are specific to the proms2teams and Satchet configurations. 

Prometheus-Operator:

Users of Alerting Drivers who specifically use the AlertmanagerConfig CRs will need to manually update their Sachet or prom2teams configurations on upgrading the Rancher Monitoring chart due to a change introduced by upstream with respect to how receivers added via AlertmanagerConfig CRs are named.
Receivers are now delimited by \ instead of - (<namespace>-<alertManagerConfig>-<receiverName> to <namespace>/<alertManagerConfig>/<receiverName>).

To update the Receiver configurations from the Rancher UI:

1. Navigate to ConfigMaps under More Resources or by searching for ConfigMaps.
2. Find the ConfigMap for Sachet or prom2teams.
3. Update the receiver names to use '/' as a delimiter.
4. Redeploy the workloads associated with Alertmanager and Sachet / prom2teams to ensure that they pick up the new configurations.

This change was introduced to prevent AlertmanagerConfig objects from generating identical references in the final Alertmanager configuration. For example, take the following AlertmanagerConfigs:

- AlertmanagerConfig foo-bar in namespace ns defines a Receiver with name fred.
- AlertmanagerConfig bar in namespace ns-foo defines a Receiver with name fred.

Without this patch, the resulting Alertmanager configuration would have two receivers named ns-foo-bar-fred, which is invalid. With this patch, the receivers within Alerting Drivers would be named ns/foo-bar/fred and ns-foo/bar/fred, because / is not a valid character for namespaces. (https://github.com/prometheus-operator/prometheus-operator/commit/80a72c42f5c62012d27330b7c5203fd110d7f764)

**Comment by martyav** [comment]
@geethub97 I'm going to update the Rancher 2.6.x docs with instructions. Does 2.7.x also need this noted?
